
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 14 01:34:49 BRT 2017
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int PONTO_E_VIRGULA = 15;
  public static final int SENAO = 4;
  public static final int SUBTRACAO = 10;
  public static final int MULTIPLICACAO = 11;
  public static final int MENOR = 7;
  public static final int ENTAO = 3;
  public static final int IGUAL = 8;
  public static final int INTEIRO = 18;
  public static final int FECHA_PARENTESIS = 14;
  public static final int VIRGULA = 16;
  public static final int EOF = 0;
  public static final int DEF = 5;
  public static final int DIVISAO = 12;
  public static final int error = 1;
  public static final int MAIOR = 6;
  public static final int IDENTIFICADOR = 17;
  public static final int SE = 2;
  public static final int SOMA = 9;
  public static final int ABRE_PARENTESIS = 13;
}

