
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 12 11:02:10 BRT 2017
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int PONTO_E_VIRGULA = 17;
  public static final int SENAO = 6;
  public static final int SUBTRACAO = 12;
  public static final int MULTIPLICACAO = 13;
  public static final int MENOR = 9;
  public static final int ENTAO = 5;
  public static final int IGUAL = 10;
  public static final int INTEIRO = 21;
  public static final int VIRGULA = 18;
  public static final int FECHA_PARENTESIS = 16;
  public static final int COMENTARIO_CURTO = 3;
  public static final int EOF = 0;
  public static final int DEF = 7;
  public static final int DIVISAO = 14;
  public static final int error = 1;
  public static final int MAIOR = 8;
  public static final int IDENTIFICADOR = 20;
  public static final int SE = 4;
  public static final int COMENTARIO_EM_BLOCO = 2;
  public static final int SOMA = 11;
  public static final int ABRE_PARENTESIS = 15;
  public static final int branco = 19;
}

